// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minorag.Core.Store;

#nullable disable

namespace Minorag.Cli.Migrations
{
    [DbContext(typeof(RagDbContext))]
    [Migration("20251225115528_AddedFiles")]
    partial class AddedFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Minorag.Core.Models.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.CodeChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("embedding");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("extension");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repository_id");

                    b.Property<string>("SymbolName")
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol_name");

                    b.HasKey("Id");

                    b.HasIndex("Extension")
                        .HasDatabaseName("idx_chunks_extension");

                    b.HasIndex("FileId");

                    b.HasIndex("Path")
                        .HasDatabaseName("idx_chunks_path");

                    b.HasIndex("RepositoryId", "Path")
                        .HasDatabaseName("idx_chunks_repo_path");

                    b.ToTable("chunks", (string)null);
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastIndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("root_path");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.RepositoryFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("extension");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repository_id");

                    b.Property<string>("SymbolName")
                        .HasColumnType("TEXT")
                        .HasColumnName("symbol_name");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.CodeChunk", b =>
                {
                    b.HasOne("Minorag.Core.Models.Domain.RepositoryFile", "File")
                        .WithMany("Chunks")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Minorag.Core.Models.Domain.Repository", "Repository")
                        .WithMany("Chunks")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.Project", b =>
                {
                    b.HasOne("Minorag.Core.Models.Domain.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.Repository", b =>
                {
                    b.HasOne("Minorag.Core.Models.Domain.Project", "Project")
                        .WithMany("Repositories")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.RepositoryFile", b =>
                {
                    b.HasOne("Minorag.Core.Models.Domain.Repository", "Repository")
                        .WithMany("Files")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.Project", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.Repository", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("Minorag.Core.Models.Domain.RepositoryFile", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
